// Direct gloss translation: full English gloss -> Portuguese
// No word-by-word splitting — each entry is the complete gloss as it appears in STEPBible
const GLOSS_PT: Record<string, string> = {
  // Grammatical markers
  'obj.': '[obj. direto]',
  'and obj.': 'e',

  // Prepositions / conjunctions
  'and': 'e',
  'and/': 'e',
  'or': 'ou',
  'but': 'mas',
  'for': 'pois',
  'so': 'assim',
  'also': 'também',
  'even': 'até',
  'then': 'então',
  'yet': 'ainda',
  'now': 'agora',
  'therefore': 'portanto',
  'because': 'porque',
  'if': 'se',
  'when': 'quando',
  'as': 'como',
  'that': 'que',
  'which': 'o qual',
  'who': 'quem',
  'not': 'não',
  'no': 'não',
  'neither': 'nem',
  'nor': 'nem',
  'in': 'em',
  'on': 'sobre',
  'at': 'em',
  'to': 'a',
  'of': 'de',
  'from': 'de',
  'with': 'com',
  'by': 'por',
  'through': 'através de',
  'into': 'para dentro de',
  'out of': 'para fora de',
  'up': 'acima',
  'down': 'abaixo',
  'before': 'diante de',
  'after': 'depois de',
  'against': 'contra',
  'upon': 'sobre',
  'unto': 'para',
  'over': 'sobre',
  'under': 'sob',
  'between': 'entre',
  'among': 'entre',
  'without': 'sem',
  'within': 'dentro de',
  'behind': 'atrás de',
  'above': 'acima de',
  'below': 'abaixo de',
  'beside': 'ao lado de',
  'near': 'perto de',
  'according to': 'segundo',
  'because of': 'por causa de',
  'instead of': 'em vez de',
  'in behalf of': 'em favor de',
  'together': 'juntos',
  'thus': 'assim',
  'indeed': 'de fato',
  'surely': 'certamente',
  'truly': 'verdadeiramente',
  'behold': 'eis',
  'again': 'novamente',
  'still': 'ainda',
  'already': 'já',
  'only': 'somente',
  'just': 'apenas',
  'very': 'muito',
  'exceedingly': 'sobremaneira',
  'greatly': 'muito',
  'forever': 'para sempre',
  'always': 'sempre',
  'never': 'nunca',
  'today': 'hoje',
  'tomorrow': 'amanhã',
  'yesterday': 'ontem',
  'here': 'aqui',
  'there': 'ali',
  'where': 'onde',
  'how': 'como',
  'why': 'por que',
  'how?': 'como?',

  // Pronouns
  'I': 'eu',
  'me': 'me',
  'my': 'meu',
  'mine': 'meu',
  'we': 'nós',
  'us': 'nos',
  'our': 'nosso',
  'you': 'tu',
  'your': 'teu',
  'he': 'ele',
  'him': 'ele',
  'his': 'seu',
  'she': 'ela',
  'her': 'ela',
  'it': 'isso',
  'its': 'seu',
  'they': 'eles',
  'them': 'eles',
  'their': 'seu',
  'this': 'este',
  'these': 'estes',
  'that one': 'aquele',
  'those': 'aqueles',
  'what': 'o que',
  'all': 'todo',
  'every': 'cada',
  'each': 'cada',
  'some': 'alguns',
  'many': 'muitos',
  'much': 'muito',
  'more': 'mais',
  'most': 'mais',
  'few': 'poucos',
  'little': 'pouco',
  'both': 'ambos',
  'other': 'outro',
  'another': 'outro',
  'same': 'mesmo',
  'own': 'próprio',
  'himself': 'ele mesmo',
  'herself': 'ela mesma',
  'themselves': 'eles mesmos',
  'myself': 'eu mesmo',
  'yourself': 'tu mesmo',
  'ourselves': 'nós mesmos',
  'people my': 'meu povo',
  'red my': 'meu',

  // Verbs — common forms
  'be': 'ser',
  'is': 'é',
  'are': 'são',
  'was': 'era',
  'were': 'eram',
  'will be': 'será',
  'have': 'ter',
  'has': 'tem',
  'had': 'tinha',
  'do': 'fazer',
  'did': 'fez',
  'does': 'faz',
  'done': 'feito',
  'go': 'ir',
  'went': 'foi',
  'gone': 'ido',
  'come': 'vir',
  'came': 'veio',
  'say': 'dizer',
  'said': 'disse',
  'says': 'diz',
  'speak': 'falar',
  'spoke': 'falou',
  'spoken': 'falado',
  'tell': 'contar',
  'told': 'contou',
  'call': 'chamar',
  'called': 'chamou',
  'give': 'dar',
  'gave': 'deu',
  'given': 'dado',
  'take': 'tomar',
  'took': 'tomou',
  'taken': 'tomado',
  'bring': 'trazer',
  'brought': 'trouxe',
  'send': 'enviar',
  'sent': 'enviou',
  'see': 'ver',
  'saw': 'viu',
  'seen': 'visto',
  'know': 'conhecer',
  'knew': 'conheceu',
  'known': 'conhecido',
  'hear': 'ouvir',
  'heard': 'ouviu',
  'make': 'fazer',
  'made': 'fez',
  'put': 'pôr',
  'set': 'colocar',
  'stand': 'ficar de pé',
  'stood': 'ficou de pé',
  'sit': 'sentar',
  'sat': 'sentou',
  'rise': 'levantar',
  'rose': 'levantou',
  'arise': 'levantar-se',
  'arose': 'levantou-se',
  'fall': 'cair',
  'fell': 'caiu',
  'fallen': 'caído',
  'walk': 'andar',
  'walked': 'andou',
  'run': 'correr',
  'ran': 'correu',
  'turn': 'voltar',
  'turned': 'voltou',
  'return': 'retornar',
  'returned': 'retornou',
  'eat': 'comer',
  'ate': 'comeu',
  'drink': 'beber',
  'drank': 'bebeu',
  'live': 'viver',
  'lived': 'viveu',
  'die': 'morrer',
  'died': 'morreu',
  'kill': 'matar',
  'killed': 'matou',
  'build': 'construir',
  'built': 'construiu',
  'write': 'escrever',
  'wrote': 'escreveu',
  'written': 'escrito',
  'read': 'ler',
  'pray': 'orar',
  'prayed': 'orou',
  'worship': 'adorar',
  'worshiped': 'adorou',
  'serve': 'servir',
  'served': 'serviu',
  'obey': 'obedecer',
  'love': 'amar',
  'loved': 'amou',
  'hate': 'odiar',
  'hated': 'odiou',
  'fear': 'temer',
  'feared': 'temeu',
  'trust': 'confiar',
  'believe': 'crer',
  'believed': 'creu',
  'help': 'ajudar',
  'helped': 'ajudou',
  'save': 'salvar',
  'saved': 'salvou',
  'forgive': 'perdoar',
  'forgiven': 'perdoado',
  'bless': 'abençoar',
  'blessed': 'abençoado',
  'curse': 'amaldiçoar',
  'cursed': 'amaldiçoado',
  'enter': 'entrar',
  'entered': 'entrou',
  'leave': 'sair',
  'left': 'saiu',
  'open': 'abrir',
  'opened': 'abriu',
  'close': 'fechar',
  'closed': 'fechou',
  'shut': 'fechou',
  'ask': 'pedir',
  'asked': 'pediu',
  'answer': 'responder',
  'answered': 'respondeu',
  'seek': 'buscar',
  'sought': 'buscou',
  'find': 'encontrar',
  'found': 'encontrou',
  'keep': 'guardar',
  'kept': 'guardou',
  'hold': 'segurar',
  'held': 'segurou',
  'carry': 'carregar',
  'carried': 'carregou',
  'lead': 'guiar',
  'led': 'guiou',
  'follow': 'seguir',
  'followed': 'seguiu',
  'receive': 'receber',
  'received': 'recebeu',
  'offer': 'oferecer',
  'offered': 'ofereceu',
  'command': 'ordenar',
  'commanded': 'ordenou',
  'declare': 'declarar',
  'proclaimed': 'proclamou',
  'proclaim': 'proclamar',
  'teach': 'ensinar',
  'taught': 'ensinou',
  'learn': 'aprender',
  'show': 'mostrar',
  'showed': 'mostrou',
  'appear': 'aparecer',
  'appeared': 'apareceu',
  'remain': 'permanecer',
  'remained': 'permaneceu',
  'dwell': 'habitar',
  'dwelt': 'habitou',
  'reign': 'reinar',
  'reigned': 'reinou',
  'judge': 'julgar',
  'judged': 'julgou',
  'fight': 'lutar',
  'fought': 'lutou',
  'destroy': 'destruir',
  'destroyed': 'destruiu',
  'cast': 'lançar',
  'extend': 'estender',
  'extended': 'estendeu',
  'touch': 'tocar',
  'touched': 'tocou',
  'lift': 'levantar',
  'lifted': 'levantou',
  'raise': 'erguer',
  'raised': 'ergueu',
  'stretch': 'estender',
  'stretched': 'estendeu',
  'created': 'criou',
  'create': 'criar',
  'formed': 'formou',
  'form': 'formar',
  // Verbal phrases with "and he/she/they/I"
  'and he': 'e ele',
  'and she': 'e ela',
  'and they': 'e eles',
  'and I': 'e eu',
  'and he said': 'e ele disse',
  'and she said': 'e ela disse',
  'and he went': 'e ele foi',
  'and he came': 'e ele veio',
  'and he took': 'e ele tomou',
  'and he gave': 'e ele deu',
  'and he saw': 'e ele viu',
  'and he made': 'e ele fez',
  'and he called': 'e ele chamou',
  'and he sent': 'e ele enviou',
  'and he built': 'e ele construiu',
  'and he rose': 'e ele levantou',
  'and he arose': 'e ele se levantou',
  'and he removed': 'e ele removeu',
  'and he appointed': 'e ele nomeou',
  'and he set': 'e ele colocou',
  'and he put': 'e ele pôs',
  'and he returned': 'e ele retornou',
  'and he stood': 'e ele ficou de pé',
  'and he fell': 'e ele caiu',
  'and he died': 'e ele morreu',
  'and he lived': 'e ele viveu',
  'and he reigned': 'e ele reinou',
  'and he heard': 'e ele ouviu',
  'and he answered': 'e ele respondeu',
  'and he found': 'e ele encontrou',
  'and she arose': 'e ela se levantou',
  'and she appointed': 'e ela nomeou',
  'and she stood': 'e ela ficou de pé',
  'and she came': 'e ela veio',
  'and they said': 'e eles disseram',
  'and they went': 'e eles foram',
  'and they came': 'e eles vieram',
  'he created': 'ele criou',
  'he said': 'ele disse',
  'he went': 'ele foi',
  'he came': 'ele veio',
  'he saw': 'ele viu',
  'he made': 'ele fez',
  'he gave': 'ele deu',
  'he took': 'ele tomou',
  'he sent': 'ele enviou',
  'he called': 'ele chamou',
  'he removed': 'ele removeu',
  'he appointed': 'ele nomeou',
  'she arose': 'ela se levantou',
  'she stood': 'ela ficou de pé',
  'she appointed': 'ela nomeou',
  'it will find': 'ele encontrará',
  'will I be able': 'poderei',
  'and I will look': 'e verei',
  'on the destruction of': 'na destruição de',

  // Nouns com artigo — forma completa (evita problema de gênero)
  'in beginning': 'no princípio',
  'beginning': 'princípio',
  'the beginning': 'o princípio',
  'the heavens': 'os céus',
  'the heaven': 'o céu',
  'the earth': 'a terra',
  'the land': 'a terra',
  'the sea': 'o mar',
  'the waters': 'as águas',
  'the water': 'a água',
  'the light': 'a luz',
  'the darkness': 'as trevas',
  'the night': 'a noite',
  'the morning': 'a manhã',
  'the evening': 'a tarde',
  'the day': 'o dia',
  'the days': 'os dias',
  'the sun': 'o sol',
  'the moon': 'a lua',
  'the fire': 'o fogo',
  'the wind': 'o vento',
  'the spirit': 'o espírito',
  'the word': 'a palavra',
  'the words': 'as palavras',
  'the law': 'a lei',
  'the house': 'a casa',
  'the city': 'a cidade',
  'the way': 'o caminho',
  'the king': 'o rei',
  'the kings': 'os reis',
  'the queen': 'a rainha',
  'the prince': 'o príncipe',
  'the priest': 'o sacerdote',
  'the priests': 'os sacerdotes',
  'the prophet': 'o profeta',
  'the prophets': 'os profetas',
  'the man': 'o homem',
  'the men': 'os homens',
  'the woman': 'a mulher',
  'the women': 'as mulheres',
  'the son': 'o filho',
  'the sons': 'os filhos',
  'the daughter': 'a filha',
  'the daughters': 'as filhas',
  'the father': 'o pai',
  'the fathers': 'os pais',
  'the mother': 'a mãe',
  'the brother': 'o irmão',
  'the servant': 'o servo',
  'the servants': 'os servos',
  'the people': 'o povo',
  'the nation': 'a nação',
  'the nations': 'as nações',
  'the enemy': 'o inimigo',
  'the enemies': 'os inimigos',
  'the blood': 'o sangue',
  'the name': 'o nome',
  'the names': 'os nomes',
  'the voice': 'a voz',
  'the hand': 'a mão',
  'the hands': 'as mãos',
  'the heart': 'o coração',
  'the soul': 'a alma',
  'the body': 'o corpo',
  'the head': 'a cabeça',
  'the eye': 'o olho',
  'the eyes': 'os olhos',
  'the mouth': 'a boca',
  'the face': 'o rosto',
  'the feet': 'os pés',
  'the foot': 'o pé',
  'the sword': 'a espada',
  'the scepter': 'o cetro',
  'the rod': 'a vara',
  'the staff': 'o cajado',
  'the book': 'o livro',
  'the books': 'os livros',
  'the altar': 'o altar',
  'the temple': 'o templo',
  'the tabernacle': 'o tabernáculo',
  'the ark': 'a arca',
  'the throne': 'o trono',
  'the kingdom': 'o reino',
  'the glory': 'a glória',
  'the truth': 'a verdade',
  'the grace': 'a graça',
  'the peace': 'a paz',
  'the joy': 'a alegria',
  'the love': 'o amor',
  'the wrath': 'a ira',
  'the anger': 'a raiva',
  'the sin': 'o pecado',
  'the sins': 'os pecados',
  'the evil': 'o mal',
  'the wicked': 'o ímpio',
  'the iniquity': 'a iniquidade',
  'the judgment': 'o julgamento',
  'the salvation': 'a salvação',
  'the righteousness': 'a justiça',
  'the mercy': 'a misericórdia',
  'the covenant': 'a aliança',
  'the promise': 'a promessa',
  'the prayer': 'a oração',
  'the praise': 'o louvor',
  'the sacrifice': 'o sacrifício',
  'the offering': 'a oferta',
  'the gold': 'o ouro',
  'the silver': 'a prata',
  'the bread': 'o pão',
  'the wine': 'o vinho',
  'the oil': 'o óleo',
  'the stone': 'a pedra',
  'the stones': 'as pedras',
  'the tree': 'a árvore',
  'the trees': 'as árvores',
  'the road': 'o caminho',
  'the path': 'a vereda',
  'the gate': 'a porta',
  'the gates': 'as portas',
  'the mountain': 'o monte',
  'the mountains': 'os montes',
  'the river': 'o rio',
  'the wilderness': 'o deserto',
  'the desert': 'o deserto',
  'the field': 'o campo',
  'the garden': 'o jardim',
  'the destruction': 'a destruição',
  'on the evil': 'sobre o mal',
  'on the destruction': 'na destruição',

  // Nouns sem artigo
  'heaven': 'céu',
  'heavens': 'céus',
  'earth': 'terra',
  'land': 'terra',
  'sea': 'mar',
  'water': 'água',
  'waters': 'águas',
  'light': 'luz',
  'darkness': 'trevas',
  'night': 'noite',
  'morning': 'manhã',
  'evening': 'tarde',
  'day': 'dia',
  'days': 'dias',
  'year': 'ano',
  'years': 'anos',
  'time': 'tempo',
  'hour': 'hora',
  'sun': 'sol',
  'moon': 'lua',
  'star': 'estrela',
  'stars': 'estrelas',
  'wind': 'vento',
  'rain': 'chuva',
  'fire': 'fogo',
  'cloud': 'nuvem',
  'clouds': 'nuvens',
  'God': 'Deus',
  'LORD': 'SENHOR',
  'Lord': 'Senhor',
  'Spirit': 'Espírito',
  'Holy Spirit': 'Espírito Santo',
  'angel': 'anjo',
  'angels': 'anjos',
  'glory': 'glória',
  'grace': 'graça',
  'truth': 'verdade',
  'faith': 'fé',
  'hope': 'esperança',
  'peace': 'paz',
  'joy': 'alegria',
  'salvation': 'salvação',
  'righteousness': 'justiça',
  'holiness': 'santidade',
  'holy': 'santo',
  'sin': 'pecado',
  'sins': 'pecados',
  'evil': 'mal',
  'wicked': 'ímpio',
  'wickedness': 'maldade',
  'iniquity': 'iniquidade',
  'transgression': 'transgressão',
  'mercy': 'misericórdia',
  'compassion': 'compaixão',
  'wrath': 'ira',
  'anger': 'raiva',
  'judgment': 'julgamento',
  'justice': 'justiça',
  'law': 'lei',
  'commandment': 'mandamento',
  'commandments': 'mandamentos',
  'covenant': 'aliança',
  'promise': 'promessa',
  'word': 'palavra',
  'words': 'palavras',
  'name': 'nome',
  'names': 'nomes',
  'prayer': 'oração',
  'praise': 'louvor',
  'sacrifice': 'sacrifício',
  'offering': 'oferta',
  'temple': 'templo',
  'tabernacle': 'tabernáculo',
  'altar': 'altar',
  'ark': 'arca',
  'throne': 'trono',
  'kingdom': 'reino',
  'eternal': 'eterno',
  'everlasting': 'eterno',
  'man': 'homem',
  'men': 'homens',
  'woman': 'mulher',
  'women': 'mulheres',
  'son': 'filho',
  'sons': 'filhos',
  'daughter': 'filha',
  'daughters': 'filhas',
  'father': 'pai',
  'fathers': 'pais',
  'mother': 'mãe',
  'brother': 'irmão',
  'brothers': 'irmãos',
  'sister': 'irmã',
  'child': 'criança',
  'children': 'filhos',
  'people': 'povo',
  'nation': 'nação',
  'nations': 'nações',
  'king': 'rei',
  'kings': 'reis',
  'queen': 'rainha',
  'prince': 'príncipe',
  'priest': 'sacerdote',
  'priests': 'sacerdotes',
  'prophet': 'profeta',
  'prophets': 'profetas',
  'servant': 'servo',
  'servants': 'servos',
  'slave': 'escravo',
  'master': 'senhor',
  'enemy': 'inimigo',
  'enemies': 'inimigos',
  'friend': 'amigo',
  'neighbor': 'próximo',
  'stranger': 'estrangeiro',
  'widow': 'viúva',
  'orphan': 'órfão',
  'shepherd': 'pastor',
  'disciple': 'discípulo',
  'disciples': 'discípulos',
  'apostle': 'apóstolo',
  'apostles': 'apóstolos',
  'blood': 'sangue',
  'flesh': 'carne',
  'bone': 'osso',
  'heart': 'coração',
  'soul': 'alma',
  'spirit': 'espírito',
  'body': 'corpo',
  'hand': 'mão',
  'hands': 'mãos',
  'eye': 'olho',
  'eyes': 'olhos',
  'ear': 'ouvido',
  'ears': 'ouvidos',
  'mouth': 'boca',
  'face': 'rosto',
  'head': 'cabeça',
  'foot': 'pé',
  'feet': 'pés',
  'arm': 'braço',
  'voice': 'voz',
  'sword': 'espada',
  'scepter': 'cetro',
  'rod': 'vara',
  'staff': 'cajado',
  'book': 'livro',
  'books': 'livros',
  'scroll': 'rolo',
  'gold': 'ouro',
  'silver': 'prata',
  'iron': 'ferro',
  'stone': 'pedra',
  'stones': 'pedras',
  'bread': 'pão',
  'food': 'alimento',
  'wine': 'vinho',
  'oil': 'óleo',
  'tree': 'árvore',
  'trees': 'árvores',
  'road': 'caminho',
  'way': 'caminho',
  'path': 'vereda',
  'field': 'campo',
  'garden': 'jardim',
  'gate': 'porta',
  'gates': 'portas',
  'mountain': 'monte',
  'mountains': 'montes',
  'river': 'rio',
  'wilderness': 'deserto',
  'desert': 'deserto',
  'city': 'cidade',
  'cities': 'cidades',
  'house': 'casa',
  'destruction': 'destruição',

  // Adjectives
  'good': 'bom',
  'great': 'grande',
  'mighty': 'poderoso',
  'strong': 'forte',
  'new': 'novo',
  'old': 'velho',
  'first': 'primeiro',
  'last': 'último',
  'high': 'alto',
  'low': 'baixo',
  'long': 'longo',
  'short': 'curto',
  'wide': 'largo',
  'small': 'pequeno',
  'large': 'grande',
  'full': 'cheio',
  'empty': 'vazio',
  'pure': 'puro',
  'clean': 'limpo',
  'unclean': 'impuro',
  'alive': 'vivo',
  'dead': 'morto',
  'true': 'verdadeiro',
  'false': 'falso',
  'right': 'direito',
  'rich': 'rico',
  'poor': 'pobre',
  'wise': 'sábio',
  'foolish': 'tolo',
  'righteous': 'justo',

  // Numbers
  'one': 'um',
  'two': 'dois',
  'three': 'três',
  'four': 'quatro',
  'five': 'cinco',
  'six': 'seis',
  'seven': 'sete',
  'eight': 'oito',
  'nine': 'nove',
  'ten': 'dez',
  'twelve': 'doze',
  'forty': 'quarenta',
  'hundred': 'cem',
  'thousand': 'mil',

  // NT specific
  'Christ': 'Cristo',
  'Jesus': 'Jesus',
  'gospel': 'evangelho',
  'church': 'igreja',
  'baptism': 'batismo',
  'baptize': 'batizar',
  'resurrection': 'ressurreição',
  'cross': 'cruz',
  'life': 'vida',
  'death': 'morte',
  'born': 'nascido',
  'birth': 'nascimento',
  'generation': 'geração',
  'generations': 'gerações',
  'record': 'registro',
  'genealogy': 'genealogia',
};

export function translateGloss(gloss: string): string {
  if (!gloss) return gloss;
  const lower = gloss.toLowerCase().trim();
  // Exact match (handles full phrases correctly)
  return GLOSS_PT[gloss] ?? GLOSS_PT[lower] ?? gloss;
}
